name = "DryToolingSimulation"
uuid = "a4ad9c67-3452-46ee-8c1b-6e4c352feec0"
authors = ["Walter Dal'Maz Silva <walter.dalmazsilva@gmail.com>"]
version = "0.1.0"

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
DryToolingCore = "8d904351-f17f-419c-aa8d-05d4f5cffd52"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
