#!/usr/bin/env bash

# Consider doing the following with `juliaup`
# juliaup add 1.10.6 && juliaup default 1.10.6

# Get the directory of the currently executing script:
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Configure path to desired Julia executable:
JULIA_CMD="${HOME}/.juliaup/bin/julia"

# Even if default, declare it
export JULIA_DEPOT_PATH="${HOME}/.julia"

# Make Jupyter kernel available:
export JUPYTER_DATA_DIR="${SCRIPT_DIR}/tools/jupyter"

# Make Pluto initialization work:
export WALLYROOT="${SCRIPT_DIR}"

# Launch julia from current project:
julia --project="${SCRIPT_DIR}" -i -e "using WallyToolbox" %*
